name: Build and Deploy (pygbag)
on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install --upgrade pygbag
      - run: python -m pygbag --out build/web .
      - run: ls -lah build || true
      - run: test -d build/web || (echo "no build/web output" && exit 1)
      - run: touch build/web/.nojekyll
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
